# .github/workflows/release.yml
name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1
      - name: Install GoReleaser
        run: curl -sSfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
      - name: Run GoReleaser
        run: |
          cd ./mpod
          goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}